zarwlad:
  telegram:
    api:
      bot-token: ${APP_BOT_TOKEN}
      bot-username: ${APP_BOT_USERNAME}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${APP_DB_URL}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}

server:
  port: ${PORT:8080}